# Limpieza de datos — Proyecto SQL

## Proyecto
Salud y felicidad: un análisis de la relación entre los indicadores de salud y la calidad de vida

## Objetivo

Preparar los datasets para cargarlos en una base de datos SQL.

## Datasets utilizados

- Breast Cancer Wisconsin
- Heart Disease
- World Happiness Report

## Flujo de trabajo

1. Cargar datos originales
2. Explorar estructura de los datos
3. Detectar problemas de calidad
4. Limpiar columnas y valores
5. Exportar datasets limpios para SQL

In [40]:
# ==============================
# IMPORTAR LIBRERÍAS
# ==============================

import pandas as pd
import numpy as np

# mostrar todas las columnas
pd.set_option("display.max_columns", None)

# evitar notación científica
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

In [41]:
# ==============================
# CARGAR DATASETS
# ==============================

breast_cancer = pd.read_csv("../data/raw/breast_cancer.csv")
heart_disease = pd.read_csv("../data/raw/heart_disease.csv")
happiness = pd.read_csv("../data/raw/world_happiness.csv")

print("Datasets cargados correctamente")

Datasets cargados correctamente

In [42]:
# ==============================
# VER PRIMERAS FILAS
# ==============================

print("Breast Cancer")
display(breast_cancer.head())

print("Heart Disease")
display(heart_disease.head())

print("World Happiness")
display(happiness.head())

Breast Cancer

,842302,M,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,842517,M,20.57,17.77,132.90,1326.00,0.08,0.08,0.09,0.07,0.18,0.06,0.54,0.73,3.40,74.08,0.01,0.01,0.02,0.01,0.01,0.00,24.99,23.41,158.80,1956.00,0.12,0.19,0.24,0.19,0.28,0.09
1,84300903,M,19.69,21.25,130.00,1203.00,0.11,0.16,0.20,0.13,0.21,0.06,0.75,0.79,4.58,94.03,0.01,0.04,0.04,0.02,0.02,0.00,23.57,25.53,152.50,1709.00,0.14,0.42,0.45,0.24,0.36,0.09
2,84348301,M,11.42,20.38,77.58,386.10,0.14,0.28,0.24,0.11,0.26,0.10,0.50,1.16,3.44,27.23,0.01,0.07,0.06,0.02,0.06,0.01,14.91,26.50,98.87,567.70,0.21,0.87,0.69,0.26,0.66,0.17
3,84358402,M,20.29,14.34,135.10,1297.00,0.10,0.13,0.20,0.10,0.18,0.06,0.76,0.78,5.44,94.44,0.01,0.02,0.06,0.02,0.02,0.01,22.54,16.67,152.20,1575.00,0.14,0.20,0.40,0.16,0.24,0.08
4,843786,M,12.45,15.70,82.57,477.10,0.13,0.17,0.16,0.08,0.21,0.08,0.33,0.89,2.22,27.19,0.01,0.03,0.04,0.01,0.02,0.01,15.47,23.75,103.40,741.60,0.18,0.52,0.54,0.17,0.40,0.12

Heart Disease

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.00,1.00,4.00,160.00,286.00,0.00,2.00,108.00,1.00,1.50,2.00,3.0,3.0,2
1,67.00,1.00,4.00,120.00,229.00,0.00,2.00,129.00,1.00,2.60,2.00,2.0,7.0,1
2,37.00,1.00,3.00,130.00,250.00,0.00,0.00,187.00,0.00,3.50,3.00,0.0,3.0,0
3,41.00,0.00,2.00,130.00,204.00,0.00,2.00,172.00,0.00,1.40,1.00,0.0,3.0,0
4,56.00,1.00,2.00,120.00,236.00,0.00,0.00,178.00,0.00,0.80,1.00,0.0,3.0,0

World Happiness

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.77,1.34,1.59,0.99,0.60,0.15,0.39
1,2,Denmark,7.60,1.38,1.57,1.00,0.59,0.25,0.41
2,3,Norway,7.55,1.49,1.58,1.03,0.60,0.27,0.34
3,4,Iceland,7.49,1.38,1.62,1.03,0.59,0.35,0.12
4,5,Netherlands,7.49,1.40,1.52,1.00,0.56,0.32,0.30

In [43]:
# ==============================
# TAMAÑO DE LOS DATASETS
# ==============================

print("Breast Cancer shape:", breast_cancer.shape)
print("Heart Disease shape:", heart_disease.shape)
print("World Happiness shape:", happiness.shape)

Breast Cancer shape: (568, 32)
Heart Disease shape: (302, 14)
World Happiness shape: (156, 9)

In [44]:
# ==============================
# COLUMNAS DE CADA DATASET
# ==============================

print("Columnas Breast Cancer:")
print(breast_cancer.columns)

print("\nColumnas Heart Disease:")
print(heart_disease.columns)

print("\nColumnas World Happiness:")
print(happiness.columns)

Columnas Breast Cancer:
Index(['842302', 'M', '17.99', '10.38', '122.8', '1001', '0.1184', '0.2776',
       '0.3001', '0.1471', '0.2419', '0.07871', '1.095', '0.9053', '8.589',
       '153.4', '0.006399', '0.04904', '0.05373', '0.01587', '0.03003',
       '0.006193', '25.38', '17.33', '184.6', '2019', '0.1622', '0.6656',
       '0.7119', '0.2654', '0.4601', '0.1189'],
      dtype='object')

Columnas Heart Disease:
Index(['63.0', '1.0', '1.0.1', '145.0', '233.0', '1.0.2', '2.0', '150.0',
       '0.0', '2.3', '3.0', '0.0.1', '6.0', '0'],
      dtype='object')

Columnas World Happiness:
Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [45]:
# ==============================
# VALORES NULOS
# ==============================

print("Breast Cancer - valores nulos")
print(breast_cancer.isna().sum())

print("\nHeart Disease - valores nulos")
print(heart_disease.isna().sum())

print("\nWorld Happiness - valores nulos")
print(happiness.isna().sum())

Breast Cancer - valores nulos
842302      0
M           0
17.99       0
10.38       0
122.8       0
1001        0
0.1184      0
0.2776      0
0.3001      0
0.1471      0
0.2419      0
0.07871     0
1.095       0
0.9053      0
8.589       0
153.4       0
0.006399    0
0.04904     0
0.05373     0
0.01587     0
0.03003     0
0.006193    0
25.38       0
17.33       0
184.6       0
2019        0
0.1622      0
0.6656      0
0.7119      0
0.2654      0
0.4601      0
0.1189      0
dtype: int64

Heart Disease - valores nulos
63.0     0
1.0      0
1.0.1    0
145.0    0
233.0    0
1.0.2    0
2.0      0
150.0    0
0.0      0
2.3      0
3.0      0
0.0.1    0
6.0      0
0        0
dtype: int64

World Happiness - valores nulos
Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [46]:
# ==============================
# LIMPIEZA DATASET BREAST CANCER
# ==============================

bc_clean = breast_cancer.copy()

# estandarizar nombres de columnas
bc_clean.columns = (
    bc_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

# eliminar columnas innecesarias si existen
bc_clean = bc_clean.loc[:, ~bc_clean.columns.str.contains("^unnamed")]

# eliminar duplicados
bc_clean = bc_clean.drop_duplicates()

# revisar resultado
bc_clean.head()

,842302,m,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,842517,M,20.57,17.77,132.90,1326.00,0.08,0.08,0.09,0.07,0.18,0.06,0.54,0.73,3.40,74.08,0.01,0.01,0.02,0.01,0.01,0.00,24.99,23.41,158.80,1956.00,0.12,0.19,0.24,0.19,0.28,0.09
1,84300903,M,19.69,21.25,130.00,1203.00,0.11,0.16,0.20,0.13,0.21,0.06,0.75,0.79,4.58,94.03,0.01,0.04,0.04,0.02,0.02,0.00,23.57,25.53,152.50,1709.00,0.14,0.42,0.45,0.24,0.36,0.09
2,84348301,M,11.42,20.38,77.58,386.10,0.14,0.28,0.24,0.11,0.26,0.10,0.50,1.16,3.44,27.23,0.01,0.07,0.06,0.02,0.06,0.01,14.91,26.50,98.87,567.70,0.21,0.87,0.69,0.26,0.66,0.17
3,84358402,M,20.29,14.34,135.10,1297.00,0.10,0.13,0.20,0.10,0.18,0.06,0.76,0.78,5.44,94.44,0.01,0.02,0.06,0.02,0.02,0.01,22.54,16.67,152.20,1575.00,0.14,0.20,0.40,0.16,0.24,0.08
4,843786,M,12.45,15.70,82.57,477.10,0.13,0.17,0.16,0.08,0.21,0.08,0.33,0.89,2.22,27.19,0.01,0.03,0.04,0.01,0.02,0.01,15.47,23.75,103.40,741.60,0.18,0.52,0.54,0.17,0.40,0.12

In [47]:
# revisar columnas finales me daba error, así que lo hago con .tolist()
bc_clean.columns.tolist()

['842302',
 'm',
 '17.99',
 '10.38',
 '122.8',
 '1001',
 '0.1184',
 '0.2776',
 '0.3001',
 '0.1471',
 '0.2419',
 '0.07871',
 '1.095',
 '0.9053',
 '8.589',
 '153.4',
 '0.006399',
 '0.04904',
 '0.05373',
 '0.01587',
 '0.03003',
 '0.006193',
 '25.38',
 '17.33',
 '184.6',
 '2019',
 '0.1622',
 '0.6656',
 '0.7119',
 '0.2654',
 '0.4601',
 '0.1189']

In [48]:
# ==============================
# RECARGAR BREAST CANCER CON COLUMNAS CORRECTAS
# ==============================

columnas_breast_cancer = [
    "id",
    "diagnosis",
    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave_points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",
    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave_points_se",
    "symmetry_se",
    "fractal_dimension_se",
    "radius_worst",
    "texture_worst",
    "perimeter_worst",
    "area_worst",
    "smoothness_worst",
    "compactness_worst",
    "concavity_worst",
    "concave_points_worst",
    "symmetry_worst",
    "fractal_dimension_worst"
]

breast_cancer = pd.read_csv(
    "../data/raw/breast_cancer.csv",
    header=None,
    names=columnas_breast_cancer
)

breast_cancer.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.00,0.12,0.28,0.30,0.15,0.24,0.08,1.09,0.91,8.59,153.40,0.01,0.05,0.05,0.02,0.03,0.01,25.38,17.33,184.60,2019.00,0.16,0.67,0.71,0.27,0.46,0.12
1,842517,M,20.57,17.77,132.90,1326.00,0.08,0.08,0.09,0.07,0.18,0.06,0.54,0.73,3.40,74.08,0.01,0.01,0.02,0.01,0.01,0.00,24.99,23.41,158.80,1956.00,0.12,0.19,0.24,0.19,0.28,0.09
2,84300903,M,19.69,21.25,130.00,1203.00,0.11,0.16,0.20,0.13,0.21,0.06,0.75,0.79,4.58,94.03,0.01,0.04,0.04,0.02,0.02,0.00,23.57,25.53,152.50,1709.00,0.14,0.42,0.45,0.24,0.36,0.09
3,84348301,M,11.42,20.38,77.58,386.10,0.14,0.28,0.24,0.11,0.26,0.10,0.50,1.16,3.44,27.23,0.01,0.07,0.06,0.02,0.06,0.01,14.91,26.50,98.87,567.70,0.21,0.87,0.69,0.26,0.66,0.17
4,84358402,M,20.29,14.34,135.10,1297.00,0.10,0.13,0.20,0.10,0.18,0.06,0.76,0.78,5.44,94.44,0.01,0.02,0.06,0.02,0.02,0.01,22.54,16.67,152.20,1575.00,0.14,0.20,0.40,0.16,0.24,0.08

In [49]:
# ==============================
# LIMPIAR VARIABLE DIAGNOSIS
# ==============================

bc_clean["diagnosis"] = bc_clean["diagnosis"].replace({
    "M": "Maligno",
    "B": "Benigno"
})

bc_clean["diagnosis"].value_counts()

KeyError: 'diagnosis'

In [ ]:
# ==============================
# INFORMACIÓN FINAL DATASET LIMPIO
# ==============================

print("Shape:", bc_clean.shape)

print("\nValores nulos:")
print(bc_clean.isna().sum())

print("\nDuplicados:", bc_clean.duplicated().sum())

Shape: (569, 32)

Valores nulos:
id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave_points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave_points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave_points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

Duplicados: 0

In [ ]:
# ==============================
# EXPLORAR HEART DISEASE cómo está estructurado el dataset.
# ==============================

heart_disease.head()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.00,1.00,4.00,160.00,286.00,0.00,2.00,108.00,1.00,1.50,2.00,3.0,3.0,2
1,67.00,1.00,4.00,120.00,229.00,0.00,2.00,129.00,1.00,2.60,2.00,2.0,7.0,1
2,37.00,1.00,3.00,130.00,250.00,0.00,0.00,187.00,0.00,3.50,3.00,0.0,3.0,0
3,41.00,0.00,2.00,130.00,204.00,0.00,2.00,172.00,0.00,1.40,1.00,0.0,3.0,0
4,56.00,1.00,2.00,120.00,236.00,0.00,0.00,178.00,0.00,0.80,1.00,0.0,3.0,0

In [ ]:
heart_disease.shape

(302, 14)

In [ ]:
heart_disease.columns

Index(['63.0', '1.0', '1.0.1', '145.0', '233.0', '1.0.2', '2.0', '150.0',
       '0.0', '2.3', '3.0', '0.0.1', '6.0', '0'],
      dtype='object')

In [ ]:
# Revisar valores nulos
heart_disease.isna().sum()

63.0     0
1.0      0
1.0.1    0
145.0    0
233.0    0
1.0.2    0
2.0      0
150.0    0
0.0      0
2.3      0
3.0      0
0.0.1    0
6.0      0
0        0
dtype: int64

In [ ]:
# Crear copia limpia para empezar la limpieza
# ==============================
# COPIA PARA LIMPIEZA
# ==============================

heart_clean = heart_disease.copy()

heart_clean.head()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.00,1.00,4.00,160.00,286.00,0.00,2.00,108.00,1.00,1.50,2.00,3.0,3.0,2
1,67.00,1.00,4.00,120.00,229.00,0.00,2.00,129.00,1.00,2.60,2.00,2.0,7.0,1
2,37.00,1.00,3.00,130.00,250.00,0.00,0.00,187.00,0.00,3.50,3.00,0.0,3.0,0
3,41.00,0.00,2.00,130.00,204.00,0.00,2.00,172.00,0.00,1.40,1.00,0.0,3.0,0
4,56.00,1.00,2.00,120.00,236.00,0.00,0.00,178.00,0.00,0.80,1.00,0.0,3.0,0

In [ ]:
# ==============================
# LIMPIAR NOMBRES DE COLUMNAS
# ==============================

heart_clean.columns = (
    heart_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

heart_clean.columns

Index(['63.0', '1.0', '1.0.1', '145.0', '233.0', '1.0.2', '2.0', '150.0',
       '0.0', '2.3', '3.0', '0.0.1', '6.0', '0'],
      dtype='object')

In [ ]:
# ==============================
# RENOMBRAR COLUMNAS - El dataset usa nombres raros los renombraremos para hacerlos mas descriptivos y claros.
# ==============================

heart_clean = heart_clean.rename(columns={
    "trestbps": "resting_bp",
    "chol": "cholesterol",
    "fbs": "fasting_blood_sugar",
    "thalach": "max_heart_rate",
    "exang": "exercise_angina",
    "target": "heart_disease",
    "cp": "chest_pain_type"
})

heart_clean.head()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.00,1.00,4.00,160.00,286.00,0.00,2.00,108.00,1.00,1.50,2.00,3.0,3.0,2
1,67.00,1.00,4.00,120.00,229.00,0.00,2.00,129.00,1.00,2.60,2.00,2.0,7.0,1
2,37.00,1.00,3.00,130.00,250.00,0.00,0.00,187.00,0.00,3.50,3.00,0.0,3.0,0
3,41.00,0.00,2.00,130.00,204.00,0.00,2.00,172.00,0.00,1.40,1.00,0.0,3.0,0
4,56.00,1.00,2.00,120.00,236.00,0.00,0.00,178.00,0.00,0.80,1.00,0.0,3.0,0

In [ ]:
# ==============================
# RECARGAR HEART DISEASE CON COLUMNAS CORRECTAS
# ==============================

columnas_heart_disease = [
    "age",
    "sex",
    "chest_pain_type",
    "resting_bp",
    "cholesterol",
    "fasting_blood_sugar",
    "resting_ecg",
    "max_heart_rate",
    "exercise_angina",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "heart_disease"
]

heart_disease = pd.read_csv(
    "../data/raw/heart_disease.csv",
    header=None,
    names=columnas_heart_disease,
    na_values="?"
)

heart_disease.head()

,age,sex,chest_pain_type,resting_bp,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_angina,oldpeak,slope,ca,thal,heart_disease
0,63.00,1.00,1.00,145.00,233.00,1.00,2.00,150.00,0.00,2.30,3.00,0.00,6.00,0
1,67.00,1.00,4.00,160.00,286.00,0.00,2.00,108.00,1.00,1.50,2.00,3.00,3.00,2
2,67.00,1.00,4.00,120.00,229.00,0.00,2.00,129.00,1.00,2.60,2.00,2.00,7.00,1
3,37.00,1.00,3.00,130.00,250.00,0.00,0.00,187.00,0.00,3.50,3.00,0.00,3.00,0
4,41.00,0.00,2.00,130.00,204.00,0.00,2.00,172.00,0.00,1.40,1.00,0.00,3.00,0

In [ ]:
# ==============================
# LIMPIEZA HEART DISEASE
# ==============================

heart_clean = heart_disease.copy()

heart_clean = heart_clean.drop_duplicates()

columnas_heart = [
    "age",
    "sex",
    "chest_pain_type",
    "resting_bp",
    "cholesterol",
    "fasting_blood_sugar",
    "max_heart_rate",
    "exercise_angina",
    "oldpeak",
    "heart_disease"
]

heart_clean = heart_clean[columnas_heart]

heart_clean.head()

,age,sex,chest_pain_type,resting_bp,cholesterol,fasting_blood_sugar,max_heart_rate,exercise_angina,oldpeak,heart_disease
0,63.00,1.00,1.00,145.00,233.00,1.00,150.00,0.00,2.30,0
1,67.00,1.00,4.00,160.00,286.00,0.00,108.00,1.00,1.50,2
2,67.00,1.00,4.00,120.00,229.00,0.00,129.00,1.00,2.60,1
3,37.00,1.00,3.00,130.00,250.00,0.00,187.00,0.00,3.50,0
4,41.00,0.00,2.00,130.00,204.00,0.00,172.00,0.00,1.40,0

In [ ]:
print("Shape:", heart_clean.shape)

print("\nValores nulos:")
print(heart_clean.isna().sum())

print("\nDuplicados:", heart_clean.duplicated().sum())

Shape: (303, 10)

Valores nulos:
age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholesterol            0
fasting_blood_sugar    0
max_heart_rate         0
exercise_angina        0
oldpeak                0
heart_disease          0
dtype: int64

Duplicados: 0

In [ ]:
# ==============================
# EXPLORACIÓN DEL DATASET WORLD HAPPINESS
# ==============================

happiness.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.77,1.34,1.59,0.99,0.60,0.15,0.39
1,2,Denmark,7.60,1.38,1.57,1.00,0.59,0.25,0.41
2,3,Norway,7.55,1.49,1.58,1.03,0.60,0.27,0.34
3,4,Iceland,7.49,1.38,1.62,1.03,0.59,0.35,0.12
4,5,Netherlands,7.49,1.40,1.52,1.00,0.56,0.32,0.30

In [ ]:
# OBSERVAMOS LAS COLUMNAS
happiness.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [ ]:
# REVISAMOS NULOS
happiness.isna().sum()

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [ ]:
# ==============================
# COPIA PARA LIMPIEZA - Creamos copia para limpiar el dataset de felicidad sin modificar el original.
# ==============================

happy_clean = happiness.copy()

happy_clean.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.77,1.34,1.59,0.99,0.60,0.15,0.39
1,2,Denmark,7.60,1.38,1.57,1.00,0.59,0.25,0.41
2,3,Norway,7.55,1.49,1.58,1.03,0.60,0.27,0.34
3,4,Iceland,7.49,1.38,1.62,1.03,0.59,0.35,0.12
4,5,Netherlands,7.49,1.40,1.52,1.00,0.56,0.32,0.30

In [ ]:
# ==============================
# LIMPIAMOS NOMBRES DE COLUMNAS
# ==============================

happy_clean.columns = (
    happy_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

happy_clean.columns

Index(['overall_rank', 'country_or_region', 'score', 'gdp_per_capita',
       'social_support', 'healthy_life_expectancy',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption'],
      dtype='object')

In [ ]:
# ==============================
# ELEGIMOS NUESTRAS VARIABLES
# ==============================

columnas_happy = [
    "country_or_region",
    "score",
    "gdp_per_capita",
    "social_support",
    "healthy_life_expectancy"
]

happy_clean = happy_clean[columnas_happy]

happy_clean.head()

,country_or_region,score,gdp_per_capita,social_support,healthy_life_expectancy
0,Finland,7.77,1.34,1.59,0.99
1,Denmark,7.60,1.38,1.57,1.00
2,Norway,7.55,1.49,1.58,1.03
3,Iceland,7.49,1.38,1.62,1.03
4,Netherlands,7.49,1.40,1.52,1.00

In [ ]:
# ==============================
# RENOMBRAR COLUMNAS - esto lo hacemos para que SQL sea mas claro. 
# ==============================

happy_clean = happy_clean.rename(columns={
    "country_or_region": "country",
    "score": "happiness_score"
})

happy_clean.head()

,country,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy
0,Finland,7.77,1.34,1.59,0.99
1,Denmark,7.60,1.38,1.57,1.00
2,Norway,7.55,1.49,1.58,1.03
3,Iceland,7.49,1.38,1.62,1.03
4,Netherlands,7.49,1.40,1.52,1.00

In [ ]:
print("Shape:", happy_clean.shape)

print("\nValores nulos:")
print(happy_clean.isna().sum())

print("\nDuplicados:", happy_clean.duplicated().sum())

Shape: (156, 5)

Valores nulos:
country                    0
happiness_score            0
gdp_per_capita             0
social_support             0
healthy_life_expectancy    0
dtype: int64

Duplicados: 0